### ISSUE TITLE
运行项目时报IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Jakye** [wuweiit/mushroom#1]
org.springframework.beans.factory.BeanDefinitionStoreException:Failed to read candidate component class: file[D:\tomcat-6.0.32\webapps\mrcms\WEB-INF\classes\org\marker\mushroom\dao\impl\ArticleDaoImpl.class];nested exception is java.lang.IncompatibleCalssChangeError:class org.springframework.core.type.classreading.ClassMetadtaReadingVistor has interface org.springframework.asm.ClassVIsitor as super class 。我查了一下是Spring版本不兼容。ehcache-spring-annotations-parent.jar 用到了spring 3.0.1的相关包，而在3.2而后有很大改动，请问你怎么解决上面问题的怎么才能正常运行。

**Comment by wuweiit** [comment]
MRCMS pom.xml 里spring版本是4.1.0.RELEASE，请核实下

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by Jakye** [comment]
是4.1.0的，但是ehcache-spring-annotations-parent.jar 依赖于spring-asm-3.0.5 ，项目对应pom.xml文件有问题！不知你电脑上是否能正常运行！

**Comment by wuweiit** [comment]
我运行正常啊，你检查下你的环境，该清除的缓存，rebuild、等等

**Comment by wuweiit** [comment]
我运行正常啊，你检查下你的环境，该清除的缓存，rebuild、等等
