### ISSUE TITLE
profiles.ip无法找到

### ISSUE THREAD

**Issue by ganpanlin** [wuweiit/mushroom#10]
<dependency>
		  <groupId>com.wuweibi</groupId>
		  <artifactId>module4j</artifactId>
		  <version>1.0-SNAPSHOT</version>
	  </dependency>
这个包下载不了，请问仓库地址的ip是多少

**Comment by wuweiit** [comment]
在我的代码仓库里有个moudule4j项目，拉下来安装到仓库里即可

**Comment by wuweiit** [comment]
最新版本代码已经将module4j项目发布至maven中央仓库。
