### ISSUE TITLE
登录后台异常

### ISSUE THREAD

**Issue by nichoice** [wuweiit/mushroom#14]
AdminCONTROLLER.java 74行 menuDao.findTopMenuByGroupId(groupId) 这句异常了。release版本正常

**Comment by wuweiit** [comment]
空指针？

**Comment by nichoice** [comment]
是的

**Comment by nichoice** [comment]
release版本在后台发布了日志内容，前端那里也无法显示内容，只在页数旁边显示1条记录

**Comment by wuweiit** [comment]
那个release版本有问题，用master分支吧
