### ISSUE TITLE
SQL injection vulnerability was discovered in MRCMS

### ISSUE THREAD

**Issue by 360CodeSafe** [wuweiit/mushroom#16]
Hi all,
There are a SQL injection vulnerability found by Qihoo360 CodeSafe Team.
Details as bellow:
The getChannel method in the ChannelService. java file is used directly to hash and run SQL statements without filtering parameters, resulting in SQL injection。
![default](https://user-images.githubusercontent.com/39950310/45863532-21dc2b80-bda9-11e8-9921-cc127a7dd955.png)
Continuous tracing can be found that the getChannel method is invoked in WebApp.java.
![default](https://user-images.githubusercontent.com/39950310/45863709-f279ee80-bda9-11e8-80db-5b8b34f8900d.png)
View WebParam.get () method
![default](https://user-images.githubusercontent.com/39950310/45863737-189f8e80-bdaa-11e8-97fe-e591c042e051.png)
When param is empty (that is the first time), a param will be constructed ， view the constructor.
![default](https://user-images.githubusercontent.com/39950310/45863813-6b794600-bdaa-11e8-8f5a-5502dabc4818.png)
You can see that all attributes in WebParam are obtained from request and are controlled by attackers.

**Comment by wuweiit** [comment]
我不懂为什么要用英文描述这个注入bug，但我很高兴去解决这个问题的，感谢Qihoo360 CodeSafe Team.

**Comment by wuweiit** [comment]
最新源码已修复该 bug
