### ISSUE TITLE
config/spring/applicatione-Cache.xml 文件中hcache-spring-1.1.xsd加载不了！ 

### ISSUE THREAD

**Issue by Jakye** [wuweiit/mushroom#2]
Failed to read schema document 'http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring/ehcache-spring-1.1.xsd'
查了一下是由于eclipse加载不了对应xsd文件，我用chrome打不http://ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring/ehcache-spring-1.1.xsd；
网上查了一下可以本地载 将对应URL改成classpath:/ehcache-spring-annotations.googlecode.com/svn/schema/ehcache-spring/ehcache-spring-1.1.xsd；但是我没加载成！请您有什么方法不？

**Comment by wuweiit** [comment]
已经将项目的缓存Spring配置转移到本地xsd形式。不会再网络加载schema文件了！

**Comment by ylygithub** [comment]
老师就是屌~
