### ISSUE TITLE
install 时报测试错误，这社么意思

### ISSUE THREAD

**Issue by ghostliu** [wuweiit/mushroom#6]
Running unit.tags.ListTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE!
Running unit.tags.SingleCategoryTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!

**Comment by wuweiit** [comment]
不要走测试，-Dmaven.test.skip=true
